services:
  dwh-crm-erp:
    container_name: dwh-crm-erp_container
    image: postgres:13-alpine
    hostname: ${POSTGRES_HOST}
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./input_data:/home/input_data:rw"
      - "./psql_vol:/var/lib/postgresql/data:rw"
    networks:
      - my_network

networks:
  my_network: